### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by viiviii** [viiviii/python-slack-progress#1]
범위
 * 전체 페이지 ex: 0~499
 * 이번주 목표 페이지 ex: 0~94

- 범위 validate
  - [x] 시작 값은 마지막 값보다 작거나 같다
  - [x] 모든 범위는 양수이다(>0)
  - [x] 목표 페이지는 전체 페이지에 포함된다
- [x] 계산할 범위, 현재 페이지 값을 받아서 진행률 계산하기
  - [x] validate - 현재 페이지가 계산할 범위 이내 값인지 유효성 검사 
- [x] 진행률 값을 받아서 시각적인 진행바 텍스트 생성
  - 이 때 텍스트 length는 5칸
  - 100%를 기준으로 계산(각 칸마다 20%)

리팩토링
- [ ] page와 range가 사용하는 곳 보니까 뭔가 이상해 -> 다시 봐도 진짜 이상함
- 파일을 하나로 합쳐야되나?
  - 이유: 람다에 붙여넣기 힘듦
  - 고민: 음...뭔가 필수로 사용하는 기능들은 한 파일에서 작성하고 추후 부가적인건 파일로 분리?
  - 테스트 파일은 나눠도 되잖앙?
  - 지금 파일명도 어중간함(progress, main)

고민중
- [ ] 에러 메세지 개행
